# Minimal static_config.yaml for userver HelloHandler
components_manager:
  task_processors:
    main-task-processor:
      worker_threads: 2
    fs-task-processor:
      worker_threads: 2
  default_task_processor: main-task-processor
  components:
    logging:
      fs-task-processor: fs-task-processor
      loggers:
        default:
          file_path: '@stdout'
          level: info
        access:
          file_path: '@stderr'
          level: info
    server:
      listener:
        port: 8080
        task_processor: main-task-processor
      logger_access: access
      logger_access_tskv: access
    handler-attack:
      path: /attack
      method: POST,OPTIONS
      task_processor: main-task-processor
    handler-health:
      path: /health
      method: GET,OPTIONS
      task_processor: main-task-processor
    handler-register:
      path: /auth/register
      method: POST,OPTIONS
      task_processor: main-task-processor
    handler-login:
      path: /auth/login
      method: POST,OPTIONS
      task_processor: main-task-processor
    handler-profile:
      path: /auth/profile
      method: GET,OPTIONS
      task_processor: main-task-processor
    handler-create-deck:
      path: /deck/create
      method: POST,OPTIONS
      task_processor: main-task-processor
    handler-get-decks:
      path: /deck/list
      method: GET,OPTIONS
      task_processor: main-task-processor
    handler-update-deck:
      path: /deck/update
      method: PUT,OPTIONS
      task_processor: main-task-processor
    handler-delete-deck:
      path: /deck/delete
      method: DELETE,OPTIONS
      task_processor: main-task-processor
    handler-create-session:
      path: /session/create
      method: POST,OPTIONS
      task_processor: main-task-processor
    handler-join-session:
      path: /session/join
      method: POST,OPTIONS
      task_processor: main-task-processor
    handler-select-deck:
      path: /session/select-deck
      method: POST,OPTIONS
      task_processor: main-task-processor
    handler-get-sessions:
      path: /session/list
      method: GET,OPTIONS
      task_processor: main-task-processor
    handler-start-battle:
      path: /battle/start
      method: POST,OPTIONS
      task_processor: main-task-processor
    handler-get-battle-state:
      path: /battle/state
      method: GET,OPTIONS
      task_processor: main-task-processor
    handler-play-card:
      path: /battle/play-card
      method: POST,OPTIONS
      task_processor: main-task-processor
    handler-end-turn:
      path: /end-turn
      method: POST,OPTIONS
      task_processor: main-task-processor
    handler-battle-ws:
      path: /battle/ws
      method: GET,OPTIONS
      task_processor: main-task-processor
    handler-leave-session:
      path: /session/leave
      method: POST
      task_processor: main-task-processor
    # ... other components ... 